# Generated by Django 3.1 on 2020-08-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test', '0002_auto_20200812_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityPeroid',
            new_name='ActivityPeriod',
        ),
    ]
